Action/FixedPetPosition.cs

进入八人副本后，若当前场上存在自身召唤物，则自动将召唤物固定于指定位置

添加模块：固定召唤物位置 Fixed Pet Position

---

Combat/FixedPetPosition.cs

- 添加 SingleSelectCombo 以选择区域
- 添加获取鼠标指向坐标
- 添加获取玩家当前坐标
- 添加导入导出功能
- 其他UI上的改动

Improve UI & UX for FixedPetPosition

---

Combat/FixedPetPosition.cs

修复取消按键tootip的本地化，改为GetLoc("Cancel")

修复取消按键的本地化-FixedPetPosition

---

General/AutoSortItems.cs

刚才又参考您的 Review 优化了一下逻辑！
- 使用了 `ImRaii.Table`
- 把判断逻辑都放在 CheckCanSort 了
- `IsValidPveDuty` => `IsInNormalMap` 把判断 PVE 和 PVP 整合了
- 直接使用 `Chat` 传字符串了

添加模块：自动整理物品

---

General/AutoRecordSubTimeLeft.cs

添加了国服月卡的支持
国际服还有一种 `recurring subscription` 开了之后不会显示时间 等我晚点开了测一下再去掉 `CNOnly`
对应字符串修改 https://github.com/Dalamud-DailyRoutines/DailyRoutines.Localizations/pull/32

修改模块：自动记录剩余点卡时间

---

Action/ASTHelper.cs

修改模块：占星技能优化 修正 RadioButton 标签重叠导致的失效问题

---

Action/ASTHelper.cs

1. 修复发卡默认顺位：
Melee 盘忍龙僧镰蛇
Range 画召机赤诗舞黑
2. 修复小概率事件：
当队伍中不存在近战/远程时，不再按照小队列表顺序发放，这可能导致发给 Tank 职业，现在会选择首个远程/近战DPS。
如果小队中不存在任何DPS，则按照游戏默认规则，发给自己。~~我想不到任何这种情况应该用占星的意义。~~
3. 更新 Advance 发卡模式的逻辑：
现在使用近似 Sigmoid 函数基于 logs 分数加权默认优先级决定发卡顺位。

更新模块：占星技能优化 修复了发卡逻辑

---

UIOptimization/ShowStatusRemainingTime.cs

添加模块：显示长时增益效果的具体结束时间

---

Notice/AutoNotifyBonusFate.cs

切图时已有 / 新出现都会通知
~~只加了 7.0 新地图~~
~~本地化键就给猫耳娘决定吧~~

添加模块：自动通知加成 FATE

---

General/AutoGysahlGreens.cs

增加了新模块：自动使用基萨尔野菜
不知道本地化的应用规则，所以把本地化的注释了放在了旁边

feat: 自动使用基萨尔野菜 (AutoGysahlGreens.cs)

---

General/AutoCountBlacklisted.cs

更新模块：自动显示周边黑名单玩家数量

---

Action/ASTHelper.cs

1. 增加了 PVP 判定，目前在 PVP 中会自动禁用。
2. 优化目标重定向逻辑，现在手动选择友好 npc （如奥尔什方）时不会被重定向。

更新模块：占星技能优化

---

General/ReuseEmote.cs

添加新模块 通过宏重复使用某表情

---

Combat/AutoFateSync.cs

本地化文本：https://github.com/Dalamud-DailyRoutines/DailyRoutines.Localizations/pull/76

AutoFateSync 可选自动开启盾姿

---

Action/AutoPVPUseEarthReply.cs

优化打PVP时的手感。
~~打了一晚上战场忘记点了几十次金刚转轮被吉田直树气死了~~
疾跑状态下是否触发
防御状态下是否触发

添加模块：自动使用金刚转轮

---

Action/AutoLucidDreaming.cs

模块说明：在MP低于设定阈值时自动使用醒梦
给某笨蛋豆芽奶妈写的
配置项：是否只在副本中使用，设定MP阈值

添加模块: 自动醒梦

---

Action/HealerHelper.cs
Combat/AutoDisplayMitigationInfo.cs

**添加功能：**
1. 自定义发卡顺序
2. 治疗重定向技能白名单
3. 过量治疗时的目标选择
**热更新支持：**
1. 默认发卡顺序
2. 治疗技能清单
4. 高难副本 FFLogs-DalamudZone 匹配字典
**移除功能：**
1. 由于维护难度过高，现不再支持在小队列表旁标记重定向技能图标
**热更新支持：**
1. 减伤信息

【治疗技能优化 / 显示减伤信息】模块扩展

---

Action/HealerHelper.cs

**添加功能：**
1. 重定向复活类技能目标
2. Logs 加权发卡模式添加了对副本 【暗黑之云诛灭战】的支持
**修复问题：**
1. 现在自定义重定向发卡顺序会立刻生效 而不是小队成员变动时

[HealerHelper] Impl Easy Raise

---

UIOptimization/GameWindowLock.cs

- link to Dalamud-DailyRoutines/DailyRoutines.Localizations#95

feat: 锁定游戏窗口

---

Action/HealerHelper.cs

**更新内容：**
1. 将不同功能封装在了多个子类中，以便后续维护。
2. 更换了数据的持久化结构，使用二级嵌套。
3. 移除远程文件版本检查，尝试直接命中远程缓存文件。
**对、对吗？感觉又要开始炸游戏了**

[Healer Helper] 缓存逻辑变更

---

Action/HealerHelper.cs

治疗职业优化 修复了小队成员无法选中时导致的游戏崩溃问题

---

Combat/AutoDisplayMitigationInfo.cs

impl: use UseActionManager replace sig hook

---

Action/HealerHelper.cs
Combat/AutoHighlightStatusAction.cs

**高亮技能**
修复了重复添加 key 的数组错误
**治疗优化**
发卡会忽略大小黑头的队友

高亮错误修复 & 发卡逻辑优化

---

UIOptimization/MoreMessageFilterPresets.cs

本地化 https://github.com/Dalamud-DailyRoutines/DailyRoutines.Localizations/pull/104

更多的消息过滤预设 添加消息栏右键菜单选项

---

UIOptimization/GlamourSwitchToCurrentJob.cs

**来源**：[【许愿】编辑投影模组的时候自动切换成当前职业筛选](https://discord.com/channels/1258981591124938762/1387817128156991630)
**本地化**
https://github.com/Dalamud-DailyRoutines/DailyRoutines.Localizations/pull/105#issue-3265137367
添加了以下两条字段，
- GlamourSwitchToCurrentJobTitle
- GlamourSwitchToCurrentJobDescription

添加模块：投影自动切换成当前职业

---

Action/HealerHelper.cs

https://discord.com/channels/1258981591124938762/1327170120585314346/1406644069903372330

治疗优化：为重定向复活添加苏生

---

Action/HealerHelper.cs

**修复问题：**
- 错误使用吉星相位导致的可治疗目标识别错误 [讨论链接](https://discord.com/channels/1258981591124938762/1327170120585314346/1407786254979956806)
- `835 (StatusID) -> 3595 (ActionID)`

治疗优化：修正了笔误导致的重定向错误

---

General/AutoReplyChatBot.cs
UIOptimization/CastBarAddon.cs

添加模块：咏唱栏调整

---

UIOptimization/OptimizedFriendList.cs

添加功能：为好友名单界面优化添加搜索功能

---

UIOptimization/ShowMoreIdInfomation.cs

添加模块：显示更多ID信息

---

UIOptimization/AutoDisplayIDInfomation.cs

修复Tooltip残留问题
添加对第二种界面格式的适应
直接对stringArray修改 修复名称闪烁

模块BUG修复：自动显示ID信息

---

General/AutoGysahlGreens.cs

尝试添加了战术解锁检测，由于没有未解锁战术的陆行鸟小号无法测试，但是操作应该是可行的

Fix: AutoGysahlGreens尝试添加了战术解锁检测

---

Action/BetterMountCast.cs
Action/CancelMountCast.cs

改了一下）
现在的逻辑是 行走打断 或者 再次点击坐骑图标打断）
这样应该比较合理了）

提交 技能-更好的召唤坐骑
